# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yu3nRhp_emPm_rcgVZgi81LzEK1pjEzw
"""

def calculate_routh_table(coefficients, k):
    u = len(coefficients)
    routh_table = [[0 for j in range(u)] for i in range(u)]
    
    # Fill in the first row of the Routh table
    for i in range(0, u, 2):
        routh_table[0][i] = coefficients[i]
    for i in range(1, u, 2):
        routh_table[0][i] = k * coefficients[i]
        
    # Fill in the second row of the Routh table
    for i in range(1, u):
        routh_table[1][i-1] = -routh_table[0][0+i%2] * routh_table[0][1+i%2] / routh_table[0][0]
        
    # Fill in the remaining rows of the Routh table
    for i in range(2, u):
        for j in range(0, u-i):
            routh_table[i][j] = ((routh_table[i-2][0] * routh_table[i-1][j+1]) - (routh_table[i-1][0] * routh_table[i-2][j+1])) / routh_table[i-2][0]

    return routh_table

def is_system_stable(routh_table):
    u = len(routh_table)
    num_sign_changes = 0
    
    for i in range(u-1):
        if routh_table[i][0] * routh_table[i+1][0] < 0:
            num_sign_changes += 1
    
    if num_sign_changes == 0:
        print("Sistem stabil.")
    elif num_sign_changes > 0:
        print("Sistem tidak stabil.")
    else:
        print("Cannot determine system stability.")
    
if __name__ == '__main__':
    # Get polynomial coefficients from the user
    coefficients = list(map(float, input("Masukkan koefisien polinomial, Pisahkan dengan koma: ").split(",")))
    
    # Get value of K from the user
    k = float(input("Masukkan nilai K: "))
    
    # Calculate Routh table
    routh_table = calculate_routh_table(coefficients, k)
    
    # Print Routh table
    print("Routh Table:")
    for row in routh_table:
        print(row)
    
    # Determine system stability
    is_system_stable(routh_table)